from enum import IntEnum

class PacketIds(IntEnum):
    """Enum с ID всех пакетов Terraria в hex формате."""
    # Основные пакеты
    CONNECT_REQUEST = 0x01
    DISCONNECT = 0x02
    SET_USER_SLOT = 0x03
    PLAYER_INFO = 0x04
    PLAYER_INVENTORY_SLOT = 0x05
    REQUEST_WORLD_DATA = 0x06
    WORLD_INFO = 0x07
    REQUEST_ESSENTIAL_TILES = 0x08
    STATUS = 0x09
    SEND_SECTION = 0x0A
    SECTION_TILE_FRAME = 0x0B
    SPAWN_PLAYER = 0x0C
    UPDATE_PLAYER = 0x0D
    PLAYER_ACTIVE = 0x0E
    NULL_15 = 0x0F
    PLAYER_HP = 0x10
    MODIFY_TILE = 0x11
    TIME = 0x12
    DOOR_TOGGLE = 0x13
    SEND_TILE_SQUARE = 0x14
    UPDATE_ITEM_DROP = 0x15  # Deprecated, see 0x5A
    UPDATE_ITEM_OWNER = 0x16
    NPC_UPDATE = 0x17
    STRIKE_NPC_HELD_ITEM = 0x18
    NULL_25 = 0x19
    NULL_26 = 0x1A
    PROJECTILE_UPDATE = 0x1B
    NPC_STRIKE = 0x1C
    DESTROY_PROJECTILE = 0x1D
    TOGGLE_PVP = 0x1E
    OPEN_CHEST = 0x1F
    UPDATE_CHEST_ITEM = 0x20
    SYNC_ACTIVE_CHEST = 0x21
    PLACE_CHEST = 0x22
    HEAL_EFFECT = 0x23
    PLAYER_ZONE = 0x24
    REQUEST_PASSWORD = 0x25
    SEND_PASSWORD = 0x26
    REMOVE_ITEM_OWNER = 0x27
    SET_ACTIVE_NPC = 0x28
    PLAYER_ITEM_ANIMATION = 0x29
    PLAYER_MANA = 0x2A
    MANA_EFFECT = 0x2B
    NULL_44 = 0x2C
    PLAYER_TEAM = 0x2D
    REQUEST_SIGN = 0x2E
    UPDATE_SIGN = 0x2F
    SET_LIQUID = 0x30
    COMPLETE_CONNECTION_SPAWN = 0x31
    UPDATE_PLAYER_BUFF = 0x32
    SPECIAL_NPC_EFFECT = 0x33
    UNLOCK = 0x34
    ADD_NPC_BUFF = 0x35
    UPDATE_NPC_BUFF = 0x36
    ADD_PLAYER_BUFF = 0x37
    UPDATE_NPC_NAME = 0x38
    UPDATE_GOOD_EVIL = 0x39
    PLAY_MUSIC_ITEM = 0x3A
    HIT_SWITCH = 0x3B
    NPC_HOME_UPDATE = 0x3C
    SPAWN_BOSS_INVASION = 0x3D
    PLAYER_DODGE = 0x3E
    PAINT_TILE = 0x3F
    PAINT_WALL = 0x40
    PLAYER_NPC_TELEPORT = 0x41
    HEAL_OTHER_PLAYER = 0x42
    PLACEHOLDER_67 = 0x43
    CLIENT_UUID = 0x44
    GET_CHEST_NAME = 0x45
    CATCH_NPC = 0x46
    RELEASE_NPC = 0x47
    TRAVELLING_MERCHANT_INVENTORY = 0x48
    TELEPORTATION_POTION = 0x49
    ANGLER_QUEST = 0x4A
    COMPLETE_ANGLER_QUEST_TODAY = 0x4B
    NUMBER_ANGLER_QUESTS_COMPLETED = 0x4C
    CREATE_TEMPORARY_ANIMATION = 0x4D
    REPORT_INVASION_PROGRESS = 0x4E
    PLACE_OBJECT = 0x4F
    SYNC_PLAYER_CHEST_INDEX = 0x50
    CREATE_COMBAT_TEXT = 0x51
    LOAD_NET_MODULE = 0x52
    SET_NPC_KILL_COUNT = 0x53
    SET_PLAYER_STEALTH = 0x54
    FORCE_ITEM_NEAREST_CHEST = 0x55
    UPDATE_TILE_ENTITY = 0x56
    PLACE_TILE_ENTITY = 0x57
    TWEAK_ITEM = 0x58
    PLACE_ITEM_FRAME = 0x59
    UPDATE_ITEM_DROP_2 = 0x5A
    SYNC_EMOTE_BUBBLE = 0x5B
    SYNC_EXTRA_VALUE = 0x5C
    SOCIAL_HANDSHAKE = 0x5D
    DEPRECATED_94 = 0x5E
    KILL_PORTAL = 0x5F
    PLAYER_TELEPORT_PORTAL = 0x60
    NOTIFY_PLAYER_NPC_KILLED = 0x61
    NOTIFY_PLAYER_EVENT = 0x62
    UPDATE_MINION_TARGET = 0x63
    NPC_TELEPORT_PORTAL = 0x64
    UPDATE_SHIELD_STRENGTHS = 0x65
    NEBULA_LEVEL_UP = 0x66
    MOON_LORD_COUNTDOWN = 0x67
    NPC_SHOP_ITEM = 0x68
    GEM_LOCK_TOGGLE = 0x69
    POOF_SMOKE = 0x6A
    SMART_TEXT_MESSAGE = 0x6B
    WIRED_CANNON_SHOT = 0x6C
    MASS_WIRE_OPERATION = 0x6D
    MASS_WIRE_OPERATION_CONSUME = 0x6E
    TOGGLE_BIRTHDAY_PARTY = 0x6F
    GROW_FX = 0x70
    CRYSTAL_INVASION_START = 0x71
    CRYSTAL_INVASION_WIPE_ALL = 0x72
    MINION_ATTACK_TARGET_UPDATE = 0x73
    CRYSTAL_INVASION_SEND_WAIT_TIME = 0x74
    PLAYER_HURT_V2 = 0x75
    PLAYER_DEATH_V2 = 0x76
    COMBAT_TEXT_STRING = 0x77
    EMOJI = 0x78
    TE_DISPLAY_DOLL_ITEM_SYNC = 0x79
    REQUEST_TILE_ENTITY_INTERACTION = 0x7A
    WEAPONS_RACK_TRY_PLACING = 0x7B
    TE_HAT_RACK_ITEM_SYNC = 0x7C
    SYNC_TILE_PICKING = 0x7D
    SYNC_REVENGE_MARKER = 0x7E
    REMOVE_REVENGE_MARKER = 0x7F
    LAND_GOLF_BALL_IN_CUP = 0x80
    FINISHED_CONNECTING_TO_SERVER = 0x81
    FISH_OUT_NPC = 0x82
    TAMPER_WITH_NPC = 0x83
    PLAY_LEGACY_SOUND = 0x84
    FOOD_PLATTER_TRY_PLACING = 0x85
    UPDATE_PLAYER_LUCK_FACTORS = 0x86
    DEAD_PLAYER = 0x87
    SYNC_CAVERN_MONSTER_TYPE = 0x88
    REQUEST_NPC_BUFF_REMOVAL = 0x89
    CLIENT_FINISHED_INVENTORY_CHANGES = 0x8A
    SET_COUNTS_AS_HOST = 0x8B
    SET_MISC_EVENT_VALUES = 0x8C

    # Unknown packets
    PACKET166 = 166
    PACKET169 = 169
    PACKET177 = 177
    PACKET180 = 180
    PACKET220 = 220
    PACKET230 = 230
    PACKET243 = 243

    @classmethod
    def from_id(cls, packet_id: int) -> 'PacketIds':
        """Получить enum по ID пакета."""
        try:
            return cls(packet_id)
        except ValueError:
            raise ValueError(f"Неизвестный ID пакета: 0x{packet_id:02X}")

    def __str__(self) -> str:
        return f"{self.name} (0x{self:02X})"
