from enum import IntEnum


class PacketIds(IntEnum):
    """Enum with the ID of all Terraria packets in hex format."""

    # primary packets
    # CONNECT_REQUEST = 1
    # DISCONNECT = 2
    # SET_USER_SLOT = 3
    # PLAYER_INFO = 4
    # PLAYER_INVENTORY_SLOT = 5
    # REQUEST_WORLD_DATA = 6
    # WORLD_INFO = 7
    # REQUEST_ESSENTIAL_TILES = 8
    # STATUS = 9
    # SEND_SECTION = 10
    # SECTION_TILE_FRAME = 11
    # SPAWN_PLAYER = 12
    # UPDATE_PLAYER = 13
    # PLAYER_ACTIVE = 14
    # NULL_15 = 15
    # PLAYER_HP = 16
    # MODIFY_TILE = 17
    # TIME = 18
    # DOOR_TOGGLE = 19
    # SEND_TILE_SQUARE = 20
    # UPDATE_ITEM_DROP = 21
    # UPDATE_ITEM_OWNER = 22
    # NPC_UPDATE = 23
    # STRIKE_NPC_HELD_ITEM = 24
    # NULL_25 = 25
    # NULL_26 = 26
    # PROJECTILE_UPDATE = 27
    # NPC_STRIKE = 28
    # DESTROY_PROJECTILE = 29
    # TOGGLE_PVP = 30
    # OPEN_CHEST = 31
    # UPDATE_CHEST_ITEM = 32
    # SYNC_ACTIVE_CHEST = 33
    # PLACE_CHEST = 34
    # HEAL_EFFECT = 35
    # PLAYER_ZONE = 36
    # REQUEST_PASSWORD = 37
    # SEND_PASSWORD = 38
    # REMOVE_ITEM_OWNER = 39
    # SET_ACTIVE_NPC = 40
    # PLAYER_ITEM_ANIMATION = 41
    # PLAYER_MANA = 42
    # MANA_EFFECT = 43
    # NULL_44 = 44
    # PLAYER_TEAM = 45
    # REQUEST_SIGN = 46
    # UPDATE_SIGN = 47
    # SET_LIQUID = 48
    # COMPLETE_CONNECTION_SPAWN = 49
    # UPDATE_PLAYER_BUFF = 50
    SPECIAL_NPC_EFFECT = 51
    UNLOCK = 52
    ADD_NPC_BUFF = 53
    UPDATE_NPC_BUFF = 54
    ADD_PLAYER_BUFF = 55
    UPDATE_NPC_NAME = 56
    UPDATE_GOOD_EVIL = 57
    PLAY_MUSIC_ITEM = 58
    HIT_SWITCH = 59
    NPC_HOME_UPDATE = 60
    SPAWN_BOSS_INVASION = 61
    PLAYER_DODGE = 62
    PAINT_TILE = 63
    PAINT_WALL = 64
    PLAYER_NPC_TELEPORT = 65
    HEAL_OTHER_PLAYER = 66
    PLACEHOLDER_67 = 67
    CLIENT_UUID = 68
    GET_CHEST_NAME = 69
    CATCH_NPC = 70
    RELEASE_NPC = 71
    TRAVELLING_MERCHANT_INVENTORY = 72
    TELEPORTATION_POTION = 73
    ANGLER_QUEST = 74
    COMPLETE_ANGLER_QUEST_TODAY = 75
    NUMBER_ANGLER_QUESTS_COMPLETED = 76
    CREATE_TEMPORARY_ANIMATION = 77
    REPORT_INVASION_PROGRESS = 78
    PLACE_OBJECT = 79
    SYNC_PLAYER_CHEST_INDEX = 80
    CREATE_COMBAT_TEXT = 81
    LOAD_NET_MODULE = 82
    SET_NPC_KILL_COUNT = 83
    SET_PLAYER_STEALTH = 84
    FORCE_ITEM_NEAREST_CHEST = 85
    UPDATE_TILE_ENTITY = 86
    PLACE_TILE_ENTITY = 87
    TWEAK_ITEM = 88
    PLACE_ITEM_FRAME = 89
    UPDATE_ITEM_DROP_2 = 90
    SYNC_EMOTE_BUBBLE = 91
    SYNC_EXTRA_VALUE = 92
    SOCIAL_HANDSHAKE = 93
    DEPRECATED_SEND_DEBUG_COMMAND = 94 # exactly deprecated?
    KILL_PORTAL = 95
    PLAYER_TELEPORT_PORTAL = 96
    NOTIFY_PLAYER_NPC_KILLED = 97
    NOTIFY_PLAYER_EVENT = 98
    UPDATE_MINION_TARGET = 99
    NPC_TELEPORT_PORTAL = 100
    UPDATE_SHIELD_STRENGTHS = 101
    NEBULA_LEVEL_UP = 102
    MOON_LORD_COUNTDOWN = 103
    NPC_SHOP_ITEM = 104
    GEM_LOCK_TOGGLE = 105
    POOF_SMOKE = 106
    SMART_TEXT_MESSAGE = 107
    WIRED_CANNON_SHOT = 108
    MASS_WIRE_OPERATION = 109
    MASS_WIRE_OPERATION_CONSUME = 110
    TOGGLE_BIRTHDAY_PARTY = 111
    GROW_FX = 112
    CRYSTAL_INVASION_START = 113
    CRYSTAL_INVASION_WIPE_ALL = 114
    MINION_ATTACK_TARGET_UPDATE = 115
    CRYSTAL_INVASION_SEND_WAIT_TIME = 116
    PLAYER_HURT_V2 = 117
    PLAYER_DEATH_V2 = 118
    COMBAT_TEXT_STRING = 119
    EMOJI = 120
    TE_DISPLAY_DOLL_ITEM_SYNC = 121
    REQUEST_TILE_ENTITY_INTERACTION = 122
    WEAPONS_RACK_TRY_PLACING = 123
    TE_HAT_RACK_ITEM_SYNC = 124
    SYNC_TILE_PICKING = 125
    SYNC_REVENGE_MARKER = 126
    REMOVE_REVENGE_MARKER = 127
    LAND_GOLF_BALL_IN_CUP = 128
    FINISHED_CONNECTING_TO_SERVER = 129
    FISH_OUT_NPC = 130
    TAMPER_WITH_NPC = 131
    PLAY_LEGACY_SOUND = 132
    FOOD_PLATTER_TRY_PLACING = 133
    UPDATE_PLAYER_LUCK_FACTORS = 134
    DEAD_PLAYER = 135
    SYNC_CAVERN_MONSTER_TYPE = 136
    REQUEST_NPC_BUFF_REMOVAL = 137
    CLIENT_FINISHED_INVENTORY_CHANGES = 138
    SET_COUNTS_AS_HOST = 139
    SET_MISC_EVENT_VALUES = 140

    # Added from: 1.4.5.0+
    UPDATE_PLAYER_LOADOUT = 147
    PING = 154

    @classmethod
    def from_id(cls, packet_id: int) -> "PacketIds":
        """Get the enum by packet ID."""
        try:
            return cls(packet_id)
        except ValueError:
            raise ValueError(f"Unknown ID for packet: 0x{packet_id:02X}")

    def __str__(self) -> str:
        return f"{self.name} (0x{self:02X})"
