# AnimationID autogenerated from Terraria.ID

from enum import IntEnum, auto

class AnimationID(IntEnum):
    MushroomStatueTurningOn = 0
    MushroomStatueTurningOff = 1
    FakeChestOpening = 2
    VolcanosTurningOn = 3
    VolcanosTurningOff = 4
