# GameEventClearedID autogenerated from Terraria.ID

from enum import IntEnum, auto

class GameEventClearedID(IntEnum):
    DefeatedGoblinArmy = 0
    DefeatedFrostArmy = 1
    DefeatedPirates = 2
    DefeatedMartians = 3
    DefeatedHalloweenTree = 4
    DefeatedHalloweenKing = 5
    DefeatedGolem = 6
    DefeatedFishron = 7
    DefeatedQueenBee = 8
    DefeatedAncientCultist = 9
    DefeatedMoonlord = 10
    DefeatedSlimeKing = 11
    DefeatedPlantera = 12
    DefeatedEyeOfCthulu = 13
    DefeatedEaterOfWorldsOrBrainOfChtulu = 14
    DefeatedSkeletron = 15
    DefeatedDestroyer = 16
    DefeatedTheTwins = 17
    DefeatedSkeletronPrime = 18
    DefeatedWallOfFleshAndStartedHardmode = 19
    DefeatedIceQueen = 20
    DefeatedChristmassTree = 21
    DefeatedSantank = 22
    DefeatedEmpressOfLight = 23
    DefeatedQueenSlime = 24
    DefeatedDeerclops = 25
