# GameVersionID autogenerated from Terraria.ID

from enum import IntEnum, auto

class GameVersionID(IntEnum):
    WorldManifest = 299
    DisplayDollPose = 307
    DisplayDollHeldItem = 308
    OneTimeDialogue = 310
    DisplayDollMount = 311
    DisplayDollMountDye = 312
    WorldManifestV2 = 313
    HostToken = 314
    NPCHomelessDespawn = 315
    Terraria1453Release = 316
    Latest = 317
    Terraria1454Release = 317
