# InvasionID autogenerated from Terraria.ID

from enum import IntEnum, auto

class InvasionID(IntEnum):
    None = 0
    CachedFrostMoon = 1
    GoblinArmy = 1
    CachedPumpkinMoon = 2
    SnowLegion = 2
    CachedInvasions = 3
    CachedOldOnesArmy = 3
    PirateInvasion = 3
    MartianMadness = 4

