# ItemHoldStyleID autogenerated from Terraria.ID

from enum import IntEnum, auto

class ItemHoldStyleID(IntEnum):
    None = 0
    HoldFront = 1
    HoldUp = 2
    HoldHeavy = 3
    HoldGolfClub = 4
    HoldGuitar = 5
    HoldLamp = 6
    HoldRadio = 7
    HoldOrb = 8
