"""
ItemSourceID - autogenerated from decompiled Terraria .cs files
Terraria namespace: Terraria.ID
Terraria version: v1.4.5.5
Generator: TerrariaPyGen v1.1.0 (Maksim Stashkevich)
Generated on: 2026-02-14 15:58
"""


from enum import IntEnum, auto

class ItemSourceID(IntEnum):
    None = 0
    SetBonus_Nebula = 1
    LuckyCoin = 2
    PlayerDeath = 3
    PlayerDrop = 4
    GrandDesignOrMultiColorWrench = 5
    TorchGod = 6
    Shimmer = 8
    Digesting = 9
    InventoryOverflow = 10

