# ItemUseStyleID autogenerated from Terraria.ID

from enum import IntEnum, auto

class ItemUseStyleID(IntEnum):
    None = 0
    Swing = 1
    EatFood = 2
    Thrust = 3
    HoldUp = 4
    Shoot = 5
    DrinkLong = 6
    DrinkOld = 7
    GolfPlay = 8
    DrinkLiquid = 9
    HiddenAnimation = 10
    MowTheLawn = 11
    Guitar = 12
    Rapier = 13
    RaiseLamp = 14
    HoldOrb = 15
    PlaySound = 16
