# PlayerVoiceID autogenerated from Terraria.ID

from terrex.structures.id.set_factory import SetFactory
from enum import IntEnum, auto
from terrex.structures.id.4 import 4

class PlayerVoiceID(IntEnum):
    None = 0
    Male = 1
    Female = 2
    Other = 3
    Count = 4
    Count = 4


factory = SetFactory(4)


class PlayerVoiceIDSets:
    VariantOrder = [1, 2, 3]
