"""
PlayerVoiceID - autogenerated from decompiled Terraria .cs files
Terraria namespace: Terraria.ID
Terraria version: v1.4.5.5
Generator: TerrariaPyGen v1.1.0 (Maksim Stashkevich)
Generated on: 2026-02-14 15:58
"""


from enum import IntEnum, auto

class PlayerVoiceID(IntEnum):
    None = 0
    Male = 1
    Female = 2
    Other = 3
    Count = 4

