"""
PlayerTeamID - autogenerated from decompiled Terraria .cs files
Terraria namespace: Terraria.ID
Terraria version: v1.4.5.5
Generator: TerrariaPyGen v1.1.0 (Maksim Stashkevich)
Generated on: 2026-02-14 15:58
"""


from enum import IntEnum, auto

class PlayerTeamID(IntEnum):
    None = 0
    Red = 1
    Green = 2
    Blue = 3
    Yellow = 4
    Purple = 5

