# PlayerTextureID autogenerated from Terraria.ID

from enum import IntEnum, auto

class PlayerTextureID(IntEnum):
    Head = 0
    EyeWhites = 1
    Eyes = 2
    TorsoSkin = 3
    Undershirt = 4
    Hands = 5
    Shirt = 6
    ArmSkin = 7
    ArmUndershirt = 8
    ArmHand = 9
    LegSkin = 10
    Pants = 11
    Shoes = 12
    ArmShirt = 13
    Extra = 14
    EyeBlink = 15
