# ProjectileDrawLayerID autogenerated from Terraria.ID

from enum import IntEnum, auto

class ProjectileDrawLayerID(IntEnum):
    None = 0
    BehindNPCsAndTiles = 1
    BehindNPCs = 2
    BehindProjectiles = 3
    OverPlayers = 4
    OverWiresUI = 5
    FirstFractals = 6
    HeldProj = 7
    HeldProjOverHand = 8
