# StatusID autogenerated from Terraria.ID

from enum import IntEnum, auto

class StatusID(IntEnum):
    Ok = 0
    LaterVersion = 1
    UnknownError = 2
    EmptyFile = 3
    DecryptionError = 4
    BadSectionPointer = 5
    BadFooter = 6

