# SurfaceBackgroundID autogenerated from Terraria.ID

from terrex.structures.id.set_factory import SetFactory
from enum import IntEnum, auto
from terrex.structures.id.16 import 16

class SurfaceBackgroundID(IntEnum):
    Forest1 = 0
    Corruption = 1
    Desert = 2
    Jungle = 3
    Ocean = 4
    CorruptDesert = 5
    Hallow = 6
    Snow = 7
    Crimson = 8
    Mushroom = 9
    Forest2 = 10
    Forest3 = 11
    Forest4 = 12
    HallowDesert = 13
    CrimsonDesert = 14
    Empty = 15
    Count = 16
    Count = 16


factory = SetFactory(16)


class SurfaceBackgroundIDSets:
    IsDesertVariant = factory.create_bool_set(False, 2, 5, 13, 14)
    IsForest = factory.create_bool_set(False, 0, 10, 11, 12)
