"""
TileChangeType - autogenerated from decompiled Terraria .cs files
Terraria namespace: Terraria.ID
Terraria version: v1.4.5.5
Generator: TerrariaPyGen v1.1.0 (Maksim Stashkevich)
Generated on: 2026-02-14 15:58
"""


from enum import IntEnum, auto

class TileChangeType(IntEnum):
    None = 0
    LavaWater = 1
    HoneyWater = 2
    HoneyLava = 3
    ShimmerWater = 4
    ShimmerLava = 5
    ShimmerHoney = 6

