# TileChangeType autogenerated from Terraria.ID

from enum import IntEnum, auto

class TileChangeType(IntEnum):
    None = 0
    LavaWater = 1
    HoneyWater = 2
    HoneyLava = 3
    ShimmerWater = 4
    ShimmerLava = 5
    ShimmerHoney = 6

