# TorchID autogenerated from Terraria.ID

from terrex.structures.id.set_factory import SetFactory
from enum import IntEnum, auto

class TorchID(IntEnum):
    Torch = 0
    Blue = 1
    Red = 2
    Green = 3
    Purple = 4
    White = 5
    Yellow = 6
    Demon = 7
    Cursed = 8
    Ice = 9
    Orange = 10
    Ichor = 11
    UltraBright = 12
    Bone = 13
    Rainbow = 14
    Pink = 15
    Desert = 16
    Coral = 17
    Corrupt = 18
    Crimson = 19
    Hallowed = 20
    Jungle = 21
    Mushroom = 22
    Shimmer = 23
    Count = 24


factory = SetFactory(TorchID.Count)


class TorchIDSets:
    Dust = [6, 59, 60, 61, 62, 63, 64, 65, 75, 135, 158, 169, 156, 234, 66, 242, 293, 294, 295, 296, 297, 298, 307, 310]
    IsABiomeTorch = factory.create_bool_set(False, 0, 18, 19, 20, 21, 23, 13, 7, 9, 22, 16)
