# WaterStyleID autogenerated from Terraria.ID

from enum import IntEnum, auto

class WaterStyleID(IntEnum):
    Purity = 0
    Lava = 1
    Corrupt = 2
    Jungle = 3
    Hallow = 4
    Snow = 5
    Desert = 6
    Underground = 7
    Cavern = 8
    Bloodmoon = 9
    Crimson = 10
    Honey = 11
    UndergroundDesert = 12
